[package]
name = "sui-execution-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
bcs = "0.2"
indexmap = "2.8.0"
libfuzzer-sys = "0.4"
move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }
prometheus = { version = "0.14", features = ["protobuf"] }
sui-adapter-latest = { path = "../latest/sui-adapter" }
sui-framework = { path = "../../crates/sui-framework" }
sui-move-natives-latest = { path = "../latest/sui-move-natives" }
sui-protocol-config = { path = "../../crates/sui-protocol-config" }
sui-types = { path = "../../crates/sui-types" }

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
bench = false

[[bin]]
name = "phase_one_linkage_context"
path = "fuzz_targets/phase_one_linkage_context.rs"
test = false
doc = false
bench = false

[[bin]]
name = "phase_one_context_new"
path = "fuzz_targets/phase_one_context_new.rs"
test = false
doc = false
bench = false

[[bin]]
name = "context_new_direct"
path = "fuzz_targets/context_new_direct.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ptb_deserialize"
path = "fuzz_targets/ptb_deserialize.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ptb_inputs"
path = "fuzz_targets/ptb_inputs.rs"
test = false
doc = false
bench = false
